### PR TITLE
Add minutes formatting to elapsed time pipe

### PR DESCRIPTION
**Pull request by Flexicon**
~Not tested locally, need to setup dev environment.~

The changes look like this in-app:

Screenshot 2019-03-12 at 14 59 18

### CODE REVIEW

**Comment by malef** [comment]
@Flexicon You can maybe check out https://github.com/icambron/twix.js for easier formatting of intervals.

**Comment by Flexicon** [comment]
@malef sure I'll take a look.

And regarding libs, I would like to bring to your attention Luxon (https://moment.github.io/luxon/). 

It's basically momentjs but immutable and more granulated.
(Kind of like the difference between `DateTime` and `DateTimeImmutable` in PHP)

**Comment by Flexicon** [comment]
The changes look like this in-app:

Screenshot 2019-03-12 at 14 59 18

**Comment by Flexicon** [comment]
In terms of twix @malef , I don't see much benefit in using it for this particular use case since it seems to excel at showing differences between 2 date times side by side. I don't think this code with moment is too complicated.

If anything maybe consider changing it to Luxon but it's not a necessity. It makes more sense when you're storing the dates / date objects in stores such as with Redux.

**Pull request merged**
